### ISSUE TITLE
New Version(unsure what version) Incompatible with Fastload

### ISSUE THREAD

**Issue by aaron-yang0327-development** [juliand665/Dynamic-FPS#129]
So I updated DynamicFPS today, it worked when I played MC with v2.2.0 I also downgraded to v3.0.0 and it seems it's still incompatible, downgrading back to v2.2.0 and it didn't lead to loading screen lock,

Steps to Reproduce: 
- Install Fastload and DynamicFPS(v3 and above) (including dependencies of course)
- Load a world or join a server
- Stuck in loading screen

It seems Fastload is no longer maintained but the latest version it has is from May, and since DynamicFPS updated last, I figured to add an issue here.

**Comment by LostLuma** [comment]
I'm curious, what exactly do you mean by "stuck in loading screen"? I've installed Fastload and Dynamic FPS together without any other mods and it seems to work fine with the default options. If you use different ones you may need to provide your config.

The only difference I note (with and without Dynamic FPS) is that Fastload introduces some rather odd behavior where I can not move *at all* until the spawn chunks are loaded anyway, so I'm unsure what the purpose of the mod is, but it works.

**Comment by aaron-yang0327-development** [comment]
ah my bad, forgot to mention mc version

**Comment by LostLuma** [comment]
Well all questionable decisions from Fastload aside, the reason this breaks is that Dynamic FPS will skip rendering the world while the loading overlay or an opaque screen is currently overlaid over the world (e.g. when you have switched resource packs, or are in any screen with the dirt background) to help with performance on lower end systems.

Usually this optimization also breaks the vanilla loading screen, but we disable this optimization specifically for it:
https://github.com/juliand665/Dynamic-FPS/blob/d9b700ae99491e9ea353625047872d0d02e09af5/src/main/resources/fabric.mod.json#L62-L64

I can create a PR for Fastload to also fix this with their loading screen, but since their project is inactive at this time I doubt it would get accepted in a timely manner. If you (or anyone else) would like to use these mods together you can in add this to your `mods` folder, it will simply ask Dynamic FPS to not optimize Fastload's loading screen.

https://files.lostluma.net/dynamic-fps-fastload-fix.jar (don't *delete* Dynamic FPS, just add this mod)
If you're curious what this does you can open and inspect it, it just contains a very small `fabric.mod.json` file and no code at all.

**Comment by aaron-yang0327-development** [comment]
o7 thanks for the help!

**Comment by LostLuma** [comment]
Reported the issue on the other repo and will also submit a PR with a fix in a few minutes. I'll close this since it's inactionable.
