### ISSUE TITLE
Game does NOT pause when switching windows

### ISSUE THREAD

**Issue by MrBlackmidi** [juliand665/Dynamic-FPS#147]
A bug that has "bugged" me (pun not intended) is when you switch windows from the game to e.g. a web browser, the game stays idle and I have died in my survival world multiple times because of this. I have not found an issue relating to this so this may be the only one published.

**Comment by LostLuma** [comment]
Hello, this is actually a vanilla feature and has nothing to do with the mod (but I can understand the confusion). To toggle this you need to be logged into a world and press `F3 + P`, the game should give confirmation that something changed in yellow in the chat.

**Comment by KronosVoid** [comment]
While it's true that there is a vanilla feature that does this, I don't think MrBlackmidi was referring to that. After investigating the issue, I found that when tabbing out of the game in fullscreen mode with default settings, it indeed doesn't pause (it does when not in fullscreen mode). I believe this is caused by the "invisible" target frame rate being set to 0 by default and can be easily solved by configuring it to something higher than that, ideally 1. Another issue completely unrelated to this mod (instead caused by the Axiom mod) I found is that when tabbing out while using Axiom with default settings, the `alt` button technically opens a menu, making the game not pause. So if you're using this mod with default settings and/or the Axiom mod, one of these might be the cause of your issue.

**Comment by LostLuma** [comment]
I see, it only affecting fullscreen does make sense and is relatively simple to fix, I will do so in a few minutes.

Don't think there's much (or anything, honestly) we should do about Axiom - mods are responsible for marking their screens as "pause screens" and the game will handle it correctly already, however I don't really understand why it matters since as far as I'm aware it's a creative mode tool anyway, so you should not die randomly?

**Comment by KronosVoid** [comment]
The Axiom part doesn't have anything to do with this mod, it's just like the game not pausing when you have your inventory open. I only added it so others reading this don't blame this mod for something it - as you said - isn't responsible for. Thank you for taking care of this so quickly!

**Comment by LostLuma** [comment]
The fix is now in version 3.3.2. Hopefully this is the issue you were trying to describe @MrBlackmidi, otherwise please comment!

**Comment by MrBlackmidi** [comment]
Hi, it works (sorry for the late reply btw) thank you very much!
