### ISSUE TITLE
Crash when trying to use shift-click to sort inventory

### ISSUE THREAD

**Issue by Sunconure11** [juliand665/Dynamic-FPS#151]
https://pastebin.com/n83AdDsy

**Comment by LostLuma** [comment]
As I said on Discord, this is an issue with Inventory Control Tweaks (or another mod conflicting with that) rather than Dynamic FPS.

Dynamic FPS does not do anything with inventories, it just shows up in the stacktrace here because it keeps track of when you last used your keyboard and mouse to change your settings while you are idle if you have that setting enabled.

**Comment by LostLuma** [comment]
Nope, I was just sent the same pastebin link and told him that generally the most relevant part of the stacktrace is at or near the top rather than the bottom / middle, so it'd most likely be an issue with your mod or your mod and another one as a combination.

But I agree with your post on GitLab that it'd be good to get a more detailed description (maybe which mods were added or updated recently etc., or ideally a minimal set of mods where it happens!) since finding what causes this in a combination of 900+ mods is pretty unreasonable to expect from us.

**Comment by LostLuma** [comment]
It's still unreasonable to make a bug report without filtering it to a reasonable amount of mods first.

**Comment by Sunconure11** [comment]
Unless I stumble on something beforehand, I will go through this at a later date, as you do have a point. For now, Inventory Control Tweaks has been pulled on my end so I don't accidentally fire this at a time when I'm not ready to go through this.

Plus from Monday to sometime later in that week, I will not have access to my PC, so I'd be unable to help anyways.

**Comment by supersaiyansubtlety** [comment]
What mod allows you to shift-click to sort your inventory? That's probably the most likely to conflict with ICT.

**Comment by Sunconure11** [comment]
https://modrinth.com/mod/inventory-management

https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie

Perhaps look at these?

**Comment by Sunconure11** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/mouse-tweaks Forgot this too

**Comment by LostLuma** [comment]
Well either way, back to my original point here:

> Dynamic FPS does not do anything with inventories, it just shows up in the stacktrace here because it keeps track of when you last used your keyboard and mouse to change your settings while you are idle if you have that setting enabled.

If you upgrade to Dynamic FPS 3.3.3, disable the idle checker in the config, restart your game, and then cause this crash you will see that the mod is not involved at all anymore (because it does not enable the feature anymore if unused). With that being said, it's probably best to move this discussion to the GitLab issue thread and continue there.

**Comment by Sunconure11** [comment]
I'll have to do so in a couple days from now. I won't be at the PC to test.
