### ISSUE TITLE
Sometimes the game crashes when joining a server

### ISSUE THREAD

**Issue by aerulion** [juliand665/Dynamic-FPS#152]
I haven't figured out a way to reliably reproduce the crash, but sometimes the game crashes after joining a multiplayer server.

Crash Report: https://pastebin.com/raw/hxjYvPMi

**Comment by LostLuma** [comment]
Thanks for the report!

Since this does not happen reliably could you switch to the jar produced by CI on the linked PR ([go here](https://github.com/juliand665/Dynamic-FPS/actions/runs/7506355215) to download the `dynamic-fps-artifacts` zip) and see if it still occurs? If I don't hear anything I will merge and release this in the next week sometime.

**Comment by aerulion** [comment]
Sure, I will try that version. I will let you know if it still occurs. Thanks for the quick response :)

**Comment by LostLuma** [comment]
I thought about this some more and realized the crash actually makes a lot of sense, and it's weird no one else has run into it.  
Guess that means I will go ahead with releasing this now so we spare anyone else from having the issue since it's rather annoying.
