### ISSUE TITLE
Slow FPS recovery

### ISSUE THREAD

**Issue by andreasdc** [juliand665/Dynamic-FPS#158]
After longer inactivity time FPS get to the original value slower, 2/3 seconds.

**Comment by LostLuma** [comment]
As [said previously](https://github.com/juliand665/Dynamic-FPS/pull/155#issuecomment-1890952354) to your same observation in an unrelated thread: this is normal and expected behavior.

If you want us to do something about this you might want to offer more information than it being slower (how much slower? what other mods do you use? why is a two second delay crucial? etc. etc.).

I humored this report and gave letting my game idle for two hours a try myself, and I have observed that there is no difference at all to being idle for a short amount of time, so some help would really be needed from your side.

**Comment by andreasdc** [comment]
> As [said previously](https://github.com/juliand665/Dynamic-FPS/pull/155#issuecomment-1890952354) to your same observation in an unrelated thread: this is normal and expected behavior.
> 
> If you want us to do something about this you might want to offer more information than it being slower (how much slower? what other mods do you use? why is a two second delay crucial? etc. etc.).
> 
> I humored this report and gave letting my game idle for two hours a try myself, and I have observed that there is no difference at all to being idle for a short amount of time, so some help would really be needed from your side.

Maybe idle mode doesn't update automatically after getting back with alt tab?

**Comment by LostLuma** [comment]
It doesn't update when switching windows, no. That can be changed if you think it'd help though.
Thanks for actually explaining in which situation it happens since your initial post was not very useful.

**Comment by andreasdc** [comment]
Sure thing, I think that's the issue, I can test it out. :)

**Comment by LostLuma** [comment]
A fix is now available in the linked PR, feel free to test it if you'd like to.

**Comment by andreasdc** [comment]
> A fix is now available in the linked PR, feel free to test it if you'd like to.

Yup, I think all is good now. :)
