### ISSUE TITLE
Dynamic FPS breaks loading screen fade-out animation

### ISSUE THREAD

**Issue by CalXee** [juliand665/Dynamic-FPS#31]
https://youtu.be/mnfjNYvqtrw

**Comment by juliand665** [comment]
Yeah, that screen is kinda broken. I figured it didn't matter much, since it's something you wouldn't usually see much anyway, but thanks for reporting! I don't feel like it's personally worth investigating much for me, but it would be simple enough to add a config option to disable the part of the mod that causes it, however…

While Minecraft is reloading textures, vanilla actually keeps rendering the game all the way through, making it potentially take _way_ longer than it has to (it sure did back on my integrated GPU). Dynamic FPS cancels game renders while this screen is shown, but that has the effect you've shown. It's a tradeoff.

You could of course try taking a look yourself (if you're comfortable with this kind of thing) and seeing if there's a nice solution that gives us the best of both worlds—perhaps you can read out whether or not it's currently fading out, and stop canceling renders in that phase. Failing that, do you think we should add a config option to disable this "optimization" or just leave it be?
