### ISSUE TITLE
Should I enable GC when unfocused?

### ISSUE THREAD

**Issue by ardissaps** [juliand665/Dynamic-FPS#58]
Is it necessary or situationally needed?

**Comment by juliand665** [comment]
I personally don't use it and wouldn't tell my friends to, because I think it's generally better to let RAM management happen automatically than manually triggering anything, but the person who opened the feature request (#24) seemed to really swear by it! It does free up some memory, but it might cause a slight CPU spike when it happens and I don't think it really matters whether that memory is freed by Java or simply not used for a while (letting the OS deprioritize it).
